apiVersion: v1
kind: Service
metadata:
  name: adhan-app
  labels:
    app.kubernetes.io/name: adhan
spec:
  selector:
    app.kubernetes.io/name: adhan
  ports:
    - name: http
      port: 80
      targetPort: http
